import * as React from 'react';
import { useSearchParams } from 'react-router-dom';
import { ResumeForm } from '../components/builder/ResumeForm';
import { ResumePreview } from '../components/builder/ResumePreview';
import { useResumeStore } from '../hooks/useResumeStore';
import { type TemplateId, type ThemeColor } from '../types';
import { downloadAsPdf } from '../lib/pdf';
import { Button } from '../components/ui/Button';
import { Download, Eye, Code, Trash2, Upload, FileJson, Sparkles } from 'lucide-react';

const colors: { id: ThemeColor; name: string; class: string }[] = [
  { id: 'slate', name: 'Slate', class: 'bg-slate-600' },
  { id: 'indigo', name: 'Indigo', class: 'bg-indigo-600' },
  { id: 'blue', name: 'Blue', class: 'bg-blue-600' },
  { id: 'emerald', name: 'Emerald', class: 'bg-emerald-600' },
  { id: 'rose', name: 'Rose', class: 'bg-rose-600' },
  { id: 'amber', name: 'Amber', class: 'bg-amber-600' },
];

const BuilderPage: React.FC = () => {
  const { resumeData, dispatch } = useResumeStore();
  const [searchParams, setSearchParams] = useSearchParams();
  const [activeTemplate, setActiveTemplate] = React.useState<TemplateId>(
    (searchParams.get('template') as TemplateId) || 'classic'
  );
  const [viewMode, setViewMode] = React.useState<'form' | 'preview'>('form');
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  React.useEffect(() => {
    const templateFromUrl = searchParams.get('template') as TemplateId;
    if (templateFromUrl) {
      setActiveTemplate(templateFromUrl);
    }
  }, [searchParams]);
  
  const handleTemplateChange = (template: TemplateId) => {
    setActiveTemplate(template);
    setSearchParams({ template });
  };

  const handleReset = () => {
    if (window.confirm("Are you sure you want to reset all data? This cannot be undone.")) {
      dispatch({ type: 'RESET_DATA' });
    }
  };

  const handleLoadDemo = () => {
    if (window.confirm("This will overwrite your current draft with sample data. Proceed?")) {
      dispatch({ type: 'LOAD_DEMO_DATA' });
    }
  };

  const handleExportJson = () => {
    try {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(resumeData, null, 2));
      const downloadAnchor = document.createElement('a');
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `${(resumeData.name || 'resume').replace(/\s+/g, '_')}_data.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();
    } catch (error) {
      console.error("Failed to export JSON data", error);
      alert("Failed to export resume data as JSON.");
    }
  };

  const handleImportJsonClick = () => {
    fileInputRef.current?.click();
  };

  const handleImportJson = (e: React.ChangeEvent<HTMLInputElement>) => {
    const fileReader = new FileReader();
    if (e.target.files && e.target.files[0]) {
      fileReader.readAsText(e.target.files[0], "UTF-8");
      fileReader.onload = (event) => {
        try {
          const parsed = JSON.parse(event.target?.result as string);
          if (parsed && typeof parsed === 'object') {
            if ('name' in parsed && 'skills' in parsed) {
              dispatch({ type: 'LOAD_DRAFT', data: parsed });
              alert("Resume data successfully imported!");
            } else {
              alert("Invalid resume data structure. Please ensure the file was generated by this resume builder.");
            }
          }
        } catch (error) {
          console.error("Failed to parse JSON file", error);
          alert("Error parsing file. Please make sure it is a valid JSON file.");
        }
      };
    }
  };

  return (
    <div className="flex flex-col h-full bg-background">
      {/* Sticky Action Toolbar */}
      <div className="bg-background/90 backdrop-blur-md sticky top-[56px] z-40 border-b border-border/40 py-3 shadow-sm">
        <div className="container mx-auto px-4 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center justify-between w-full md:w-auto">
            <h1 className="text-xl font-extrabold bg-gradient-to-r from-primary to-foreground/70 text-transparent bg-clip-text">Resume Architect</h1>
            
            {/* Mobile-only view toggle button */}
            <Button 
              variant="outline"
              size="sm"
              onClick={() => setViewMode(viewMode === 'form' ? 'preview' : 'form')}
              className="md:hidden flex items-center gap-1.5 border-border"
            >
              {viewMode === 'form' ? <Eye className="h-4 w-4 text-emerald-500" /> : <Code className="h-4 w-4 text-sky-500" />}
              <span>{viewMode === 'form' ? 'Preview' : 'Edit Form'}</span>
            </Button>
          </div>
          
          {/* Controls toolbar */}
          <div className="flex flex-wrap items-center justify-center md:justify-end gap-3 w-full md:w-auto">
            
            {/* Theme Color Swatches */}
            <div className="flex items-center gap-1.5 border-r border-border/60 pr-3 h-9">
              <span className="text-xs font-semibold text-muted-foreground mr-1 hidden lg:inline uppercase tracking-wider">Accent:</span>
              {colors.map((c) => (
                <button
                  key={c.id}
                  onClick={() => dispatch({ type: 'SET_FIELD', field: 'themeColor', value: c.id })}
                  className={`h-5 w-5 rounded-full ${c.class} transition-all duration-200 hover:scale-115 ${
                    (resumeData.themeColor || 'slate') === c.id 
                      ? 'ring-2 ring-primary ring-offset-2 dark:ring-offset-background scale-110 shadow-md' 
                      : 'opacity-70 hover:opacity-100'
                  }`}
                  title={c.name}
                  aria-label={`Select ${c.name} theme`}
                />
              ))}
            </div>

            {/* Template select dropdown */}
            <select 
              value={activeTemplate}
              onChange={(e) => handleTemplateChange(e.target.value as TemplateId)}
              className="h-9 px-3 bg-background border border-border rounded-lg text-xs font-semibold focus:outline-none focus:ring-1 focus:ring-primary hover:bg-accent/40 transition-colors"
              aria-label="Select Resume Template"
            >
              <option value="classic">Classic</option>
              <option value="modern">Modern</option>
              <option value="creative">Creative</option>
              <option value="technical">Technical</option>
              <option value="minimalist">Minimalist</option>
              <option value="academic">Academic</option>
              <option value="executive">Executive</option>
              <option value="infographic">Infographic</option>
              <option value="startup">Startup</option>
            </select>

            {/* Actions list */}
            <div className="flex items-center gap-2">
              {/* Load Demo */}
              <Button variant="outline" size="sm" onClick={handleLoadDemo} title="Load professional template sample details" className="border-border hover:bg-accent/40">
                <Sparkles className="h-3.5 w-3.5 mr-1.5 text-lime-500" />
                <span className="text-xs">Load Demo</span>
              </Button>
              
              {/* Export JSON */}
              <Button variant="outline" size="sm" onClick={handleExportJson} title="Export resume draft data to a JSON file" className="border-border hover:bg-accent/40">
                <FileJson className="h-3.5 w-3.5 mr-1.5 text-indigo-500" />
                <span className="text-xs">Export JSON</span>
              </Button>
              
              {/* Import JSON */}
              <input 
                type="file" 
                ref={fileInputRef} 
                onChange={handleImportJson} 
                accept=".json" 
                className="hidden" 
              />
              <Button variant="outline" size="sm" onClick={handleImportJsonClick} title="Import a previously saved resume JSON file" className="border-border hover:bg-accent/40">
                <Upload className="h-3.5 w-3.5 mr-1.5 text-sky-500" />
                <span className="text-xs">Import JSON</span>
              </Button>
              
              {/* Reset */}
              <Button variant="outline" size="sm" onClick={handleReset} title="Clear draft data" className="border-border text-destructive hover:bg-destructive/10 hover:border-destructive/20">
                <Trash2 className="h-3.5 w-3.5 mr-1.5" />
                <span className="text-xs">Reset</span>
              </Button>

              {/* Download PDF */}
              <Button size="sm" onClick={() => downloadAsPdf('resume-preview-content')} className="shadow-md shadow-primary/10">
                <Download className="h-3.5 w-3.5 mr-1.5" />
                <span className="text-xs">Download PDF</span>
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Main Form/Preview Split Panel */}
      <div className="flex-grow container mx-auto px-4 py-6">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8 items-start">
          {/* Form edit column */}
          <div className={`lg:col-span-2 ${viewMode === 'preview' ? 'hidden' : ''} md:block`}>
            <ResumeForm resumeData={resumeData} dispatch={dispatch} />
          </div>
          
          {/* Preview column */}
          <div className={`lg:col-span-3 ${viewMode === 'form' ? 'hidden' : ''} md:block`}>
            <div className="sticky top-[140px] max-h-[calc(100vh-160px)] overflow-y-auto pr-1">
              <ResumePreview data={resumeData} template={activeTemplate} isBuilder={true} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BuilderPage;